#!/bin/sh
# postinst script for bodybuildingshop.ru

set -e

ANSI_RED='\033[0;31m'
ANSI_YELLOW='\033[1;33m'
ANSI_GREEN='\033[0;32m'
ANSI_RESET='\033[0m'

PATH_PROJECT=/var/www/bbs
PATH_WWW=${PATH_PROJECT}/www
PATH_BIN=${PATH_PROJECT}/bin

PATH_CONFIG=${PATH_PROJECT}/kernel

case "$1" in
    configure)
        echo "\n ${ANSI_YELLOW} Running post-install... ${ANSI_RESET} \n"

        touch $PATH_WWW/sitemap.xml

        echo "Fixing access rights..."
        chown -R www-data:www-data ${PATH_PROJECT}/*
        echo "${ANSI_GREEN} Ok. ${ANSI_RESET}"

        echo "\n ${ANSI_YELLOW} ... post-install finished. ${ANSI_RESET} \n"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
